apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # IMPORTANT: Replace with your Git repository URL
    repoURL: https://github.com/YOUR_USERNAME/argo.git
    targetRevision: HEAD
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
