apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-of-apps
  namespace: duploservices-argocd01
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-project

  source:
    # IMPORTANT: Replace with your Git repository URL
    repoURL: https://github.com/duplo-darren/argo-sample.git
    targetRevision: HEAD
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: duploservices-argocd01

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
